# Site settings
title: StaRealFeeling Blog
description: "A blog about StaRealFeeling"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://starealfeeling.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: StaRealFeeling
user_title: StaRealFeeling
email: 648330319@qq.com
twitter_username: StaRealFeeling
github_username:  StaRealFeeling
gplus_username:  StaRealFeeling
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
# profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png
profile_picture:  "/assets/img/sharding-gerenciamento-usuarios/logo.jpg"
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: 主页
      url: /
      key_trigger: 1
    - title: 我的文章
      url: /posts
      key_trigger: 2
    - title: 系列
      url: /series
      key_trigger: 3
    - title: 分类
      url: /tags
      key_trigger: 4
    - title: 关于我
      url: /about
      key_trigger: 5
  section_2:
    - title: 我的 github
      url: https://github.com/StaRealFeeling/
      new_tab: true
      key_trigger: github
    - title: 我的 csdn
      url: https://blog.csdn.net/StaRealFeeling
      key_trigger: csdn

# projects in header index
projects:
  - name: ssm_hnust
    url: https://github.com/StaRealFeeling/ssm_hnust
  - name: IntelliJ-IDEA-Tutorial
    url: https://github.com/StaRealFeeling/IntelliJ-IDEA-Tutorial

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
